# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dd45dce536baed61ff947b918da716e8875f3bb27a2a891312339ae058c575d1f6942dba64a3f7dd20aa8c03e01f84240a87e8f5834d8b281f75b1b4b5bbd4d

test:
  secret_key_base: 8452dc3a9248d2e7435d8f3f789fcac2b5de926b2547ef2db00b9382c8b40e705c498c78106c7d5e83d2d03fdd58e34113723408fa45fb79167047f2eb144148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
